### ISSUE TITLE
model deployment using fastapi

### ISSUE THREAD

**Issue by shivagowri1928** [taruntiwarihp/Projects_DS#1]
hey tarun,

i need help to make an api using fastapi .
my ml component takes image as an input and gives output as image, so i needed help in fastapi how to do that.
i'm linking the collab of my model can you plz take a look over it and tell me how the code would be to deploy it in fastapi.

thankyou 
[https://colab.research.google.com/drive/1HAoaOTnub2InYRSP5_BdGFg_il-fEs8D?usp=sharing](url)

**Comment by taruntiwarihp** [comment]
Hi sorry for the late reply, 
for your use case, you can use gradio framework. Thanks
